window.ARCHREADY_LEARNING = {
  roadmap: [
    {
      id: 'foundations', phase: 'Phase 1', weeks: 'Weeks 1–2', title: 'Cloud foundations',
      outcome: 'Understand the AWS global footprint, identity boundaries, billing, and the shared responsibility model.',
      tasks: [
        ['global', 'Map Regions, Availability Zones, and edge locations'],
        ['iam', 'Create users, roles, policies, and least-privilege access'],
        ['billing', 'Learn pricing models, budgets, and cost allocation tags'],
        ['cli', 'Practice the console, AWS CLI, and CloudShell workflow'],
      ],
      lab: 'Create a governed sandbox account design with an administrator role, developer role, budget, and audit trail.',
      domains: ['AWS Fundamentals', 'IAM & Governance', 'Cost Optimization'],
    },
    {
      id: 'core', phase: 'Phase 2', weeks: 'Weeks 3–5', title: 'Core architecture',
      outcome: 'Design resilient compute, storage, database, and network foundations across Availability Zones.',
      tasks: [
        ['vpc', 'Design VPCs, subnets, route tables, gateways, and endpoints'],
        ['compute', 'Compare EC2, Auto Scaling, load balancing, and containers'],
        ['storage', 'Choose between S3, EBS, EFS, FSx, and archive tiers'],
        ['database', 'Choose and scale RDS, Aurora, DynamoDB, and caching'],
        ['ha', 'Apply Multi-AZ, backup, recovery, and failure isolation'],
      ],
      lab: 'Build a two-AZ web architecture with public ingress, private compute, a managed database, and backups.',
      domains: ['Compute', 'Storage', 'Databases', 'Networking'],
    },
    {
      id: 'serverless', phase: 'Phase 3', weeks: 'Weeks 6–8', title: 'Secure serverless systems',
      outcome: 'Build event-driven applications with strong network, identity, encryption, and observability controls.',
      tasks: [
        ['lambda', 'Build Lambda functions with API Gateway and event sources'],
        ['events', 'Decouple workloads with SQS, SNS, and EventBridge'],
        ['security', 'Choose Security Groups, NACLs, WAF, and Network Firewall by requirement'],
        ['observability', 'Instrument metrics, logs, traces, alarms, and audit events'],
        ['iac', 'Express the architecture as repeatable infrastructure as code'],
      ],
      lab: 'Complete the Secure Project Simulator: VPC, firewall, EC2 operations host, Lambda API, data, and cost analysis.',
      domains: ['Application Integration', 'Security', 'Monitoring & Operations'],
    },
    {
      id: 'production', phase: 'Phase 4', weeks: 'Weeks 9–10', title: 'Production readiness',
      outcome: 'Evaluate architectures using reliability, security, performance, operations, and cost tradeoffs.',
      tasks: [
        ['dr', 'Define RTO/RPO and test backup and disaster recovery choices'],
        ['migration', 'Select migration strategies and hybrid connectivity'],
        ['scale', 'Run scaling, dependency failure, and traffic-spike scenarios'],
        ['optimize', 'Create a cost baseline and optimization backlog'],
      ],
      lab: 'Review a workload against the Well-Architected pillars and present prioritized remediation decisions.',
      domains: ['Architecture Patterns', 'Migration', 'Cost Optimization'],
    },
    {
      id: 'exam', phase: 'Phase 5', weeks: 'Weeks 11–12', title: 'Exam and portfolio sprint',
      outcome: 'Convert knowledge into fast architectural decisions and a deployable portfolio project.',
      tasks: [
        ['domains', 'Raise every exam domain to at least 75% practice accuracy'],
        ['mocks', 'Complete three timed mock exams at 72% or higher'],
        ['review', 'Build a concise error log for missed concepts'],
        ['portfolio', 'Document the capstone diagram, decisions, deployment, and costs'],
      ],
      lab: 'Rebuild the capstone from memory, explain every tradeoff, and complete a timed mock the following day.',
      domains: ['Architecture Patterns', 'AWS Fundamentals'],
    },
  ],
  labSteps: [
    { id: 'brief', label: 'Project brief', short: 'Define success' },
    { id: 'network', label: 'VPC & subnets', short: 'Build boundaries' },
    { id: 'security', label: 'Firewall & access', short: 'Reduce exposure' },
    { id: 'compute', label: 'EC2 workload', short: 'Configure compute' },
    { id: 'serverless', label: 'Lambda API', short: 'Add serverless' },
    { id: 'deploy', label: 'Deploy & analyze', short: 'Validate design' },
  ],
  costRates: {
    ec2: { 't3.micro': 0.0104, 't3.small': 0.0208, 't3.medium': 0.0416 },
    ebsGbMonth: 0.08,
    natHour: 0.045,
    natGb: 0.045,
    firewallHour: 0.395,
    firewallGb: 0.065,
    wafWebAclMonth: 5.00,
    wafRuleMonth: 1.00,
    wafRequestMillion: 0.60,
    lambdaRequestMillion: 0.20,
    lambdaGbSecond: 0.0000166667,
    apiRequestMillion: 3.50,
    dynamoReadMillion: 0.125,
    dynamoWriteMillion: 0.625,
    s3GbMonth: 0.023,
    logsGb: 0.50,
  },
};
